services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    command: npm run start
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '3000:3000'
